DROP TABLE LABEL CASCADE;
DROP TABLE PRODUCER CASCADE;
DROP TABLE GENRE CASCADE;

CREATE TABLE LABEL(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,
participant VARCHAR(255) NOT NULL,
role VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCER(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,
lastname VARCHAR(255) NOT NULL,
country VARCHAR(255) NOT NULL,	
LABEL_ID INT,
CONSTRAINT producer_fk FOREIGN KEY(label_id) REFERENCES label(id)
);


CREATE TABLE GENRE(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL
);
	
CREATE TABLE ALBUM(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL
-- CONSTRAINT album_fk FOREIGN KEY (song_id) REFERENCES song(id)
);	

CREATE TABLE ARTIST(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,
lastname VARCHAR(255) NOT NULL
);

	
CREATE TABLE SONG(
id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,	
	ARTIST_ID INT,
	PRODUCER_ID INT,
	ALBUM_ID INT,
CONSTRAINT song_fk FOREIGN KEY(artist_id) REFERENCES artist(id),
CONSTRAINT song_fk1 FOREIGN KEY(producer_id) REFERENCES producer(id),
CONSTRAINT SONG_FK2 FOREIGN KEY(ALBUM_ID) REFERENCES ALBUM(ID)
);

SELECT * FROM SONG;
SELECT * FROM ALBUM;
SELECT * FROM ARTIST;
SELECT * FROM GENRE;
SELECT * FROM PRODUCER;
SELECT * FROM LABEL;

 

	









